AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Serverless Image Management Application'

Globals:
  Function:
    Timeout: 60

Resources:
  ListImagesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: image_management.app.list_images
      Runtime: python3.9
      CodeUri: image_management/
      MemorySize: 128
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: GET

  ThumbnailGeneratorFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: image_management.app.generate_thumbnail
      Runtime: python3.9
      CodeUri: image_management/
      MemorySize: 128
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*

  RenameImageFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: image_management.app.rename_image
      Runtime: python3.9
      CodeUri: image_management/
      MemorySize: 128
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images/rename
            Method: POST

  ImageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: awsserverlesstestappimages