AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: your-image-bucket

  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list_images.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Events:
        ListImagesApi:
          Type: Api
          Properties:
            Path: /images
            Method: get

  ThumbnailGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: generate_thumbnail.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          THUMBNAIL_BUCKET: !Ref ImageBucket
      Events:
        ImageUpload:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg

  RenameImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rename_image.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Events:
        RenameImageApi:
          Type: Api
          Properties:
            Path: /images/rename
            Method: post

Outputs:
  ImageBucketName:
    Description: "S3 bucket name where images are uploaded"
    Value: !Ref ImageBucket

  ListImagesFunctionName:
    Description: "Lambda function to list images"
    Value: !Ref ListImagesFunction

  ThumbnailGeneratorFunctionName:
    Description: "Lambda function to generate thumbnails"
    Value: !Ref ThumbnailGeneratorFunction

  RenameImageFunctionName:
    Description: "Lambda function to rename images"
    Value: !Ref RenameImageFunction