name: Deploy Serverless Application

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build SAM application
      run: |
        sam build

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Validate AWS CLI configuration
      run: aws sts get-caller-identity

    - name: Package SAM application
      run: |
        sam package --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --region ${{ secrets.AWS_REGION}} --output-template-file packaged.yaml

    - name: Deploy SAM application
      run: |
        sam deploy --template-file packaged.yaml --stack-name image-management-serverless-app --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset

    - name: Clean up
      run: |
        rm -f packaged.yaml